import Navbar from "@/components/Navbar";
import { dbConncect } from "@/services/mongo";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Eventry | Learn with Sumit",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  await dbConncect();
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <main className="py-8">{children}</main>
      </body>
    </html>
  );
}
